# Generated by Django 3.1.4 on 2020-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_value', models.CharField(max_length=1000)),
                ('correl', models.FloatField()),
                ('debt_to_equity', models.FloatField()),
                ('dividend_yield', models.FloatField()),
                ('earnings_yield', models.FloatField()),
                ('fair_value_ddm', models.FloatField()),
                ('fair_value_fcf', models.FloatField()),
                ('free_cash_flow', models.FloatField()),
                ('industry', models.CharField(max_length=100)),
                ('industry_rank', models.FloatField()),
                ('market_share_growth', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('net_holding', models.FloatField()),
                ('net_inst_by_date', models.CharField(max_length=1000)),
                ('net_inst_value', models.CharField(max_length=1000)),
                ('net_value_executed', models.FloatField()),
                ('payout_ratio', models.FloatField()),
                ('price', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('profitability_rank', models.CharField(max_length=100)),
                ('quality_rank', models.CharField(max_length=100)),
                ('return_on_invested_capital', models.FloatField()),
                ('rev_growth', models.FloatField()),
                ('rev_uncertainty', models.FloatField()),
                ('roe_growth', models.FloatField()),
                ('roe_uncertainty', models.FloatField()),
                ('sector', models.CharField(max_length=100)),
                ('sell_value', models.CharField(max_length=1000)),
                ('top10_buys', models.CharField(max_length=1000)),
                ('top10_inst', models.CharField(max_length=1000)),
                ('top10_sells', models.CharField(max_length=1000)),
                ('value_rank', models.CharField(max_length=100)),
                ('vol', models.FloatField()),
                ('equity_to_debt', models.FloatField()),
                ('inv_rev_uncertainty', models.FloatField()),
                ('inv_roe_uncertainty', models.FloatField()),
                ('inv_correl', models.FloatField()),
                ('inv_max_drawdown', models.FloatField()),
                ('inv_vol', models.FloatField()),
                ('fcf_value', models.FloatField()),
                ('ddm_value', models.FloatField()),
                ('fair_value_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('net_holding_pct', models.FloatField()),
                ('net_value_executed_pct', models.FloatField()),
                ('company_health', models.FloatField()),
                ('company_yield', models.FloatField()),
                ('company_quality', models.FloatField()),
                ('ticker', models.CharField(max_length=100)),
                ('ticker_name', models.CharField(max_length=100)),
            ],
        ),
    ]
