# Generated by Django 3.1.4 on 2020-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='fair_value_ddm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='fair_value_fcf',
            field=models.FloatField(null=True),
        ),
    ]
