# Generated by Django 3.1.4 on 2020-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201201_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='ddm_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='fcf_value',
            field=models.FloatField(null=True),
        ),
    ]
