# Generated by Django 3.1.4 on 2020-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201203_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcsv',
            name='key',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='finalcsv',
            name='wealth_graph',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
