# Generated by Django 3.1.4 on 2020-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_portfolio_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
