# Generated by Django 3.1.4 on 2020-12-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_portfolio_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='portfolio_name',
        ),
    ]
