# Generated by Django 3.1.4 on 2020-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201204_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
