# Generated by Django 3.1.4 on 2020-12-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_portfolio_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='token',
        ),
    ]
