# Generated by Django 3.1.4 on 2020-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20201206_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='buy_value',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_by_date',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_value',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='sell_value',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_buys',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_inst',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_sells',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='wealth_graph',
            field=models.JSONField(null=True),
        ),
    ]
