# Generated by Django 3.1.4 on 2020-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20201206_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='buy_value',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
