# Generated by Django 3.1.4 on 2020-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_auto_20201206_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='sell_value',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_buys',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_inst',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_sells',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
