# Generated by Django 3.1.4 on 2020-12-06 15:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20201206_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='buy_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_by_date',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='sell_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_buys',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_inst',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_sells',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='wealth_graph',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
