# Generated by Django 3.1.4 on 2020-12-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_auto_20201206_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='token',
        ),
    ]
