# Generated by Django 3.1.4 on 2020-12-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_auto_20201206_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='shares',
            new_name='max_industry_rank',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='company',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_fair_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_health',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_insider_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_inst_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_quality',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_risk',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='min_yield',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
