# Generated by Django 3.1.4 on 2020-12-08 17:28

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_auto_20201206_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PortfolioStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_constituents', jsonfield.fields.JSONField(null=True)),
                ('portfolio_wealth_graph', jsonfield.fields.JSONField(null=True)),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='articles.portfolio')),
            ],
        ),
    ]
