# Generated by Django 3.1.4 on 2020-12-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0039_auto_20201208_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostats',
            old_name='portfolio_name',
            new_name='name',
        ),
    ]
