# Generated by Django 3.1.4 on 2020-12-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_auto_20201208_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostats',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='articles.portfolio'),
        ),
    ]
