# Generated by Django 3.1.4 on 2020-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_auto_20201208_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_fair_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_health',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_industry_rank',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_insider_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_inst_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_quality',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_yield',
            field=models.FloatField(null=True),
        ),
    ]
