# Generated by Django 3.1.4 on 2020-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_auto_20201209_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_allocation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_change',
            field=models.FloatField(null=True),
        ),
    ]
