# Generated by Django 3.1.4 on 2020-12-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0044_auto_20201209_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_historical_return',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_historical_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliostats',
            name='portfolio_historical_sharpe',
            field=models.FloatField(null=True),
        ),
    ]
