# Generated by Django 3.1.4 on 2020-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_auto_20201209_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
