# Generated by Django 3.1.4 on 2020-12-27 16:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0048_portfoliostats_execute_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='td_state',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
