# Generated by Django 3.1.4 on 2020-12-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0049_portfolio_td_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='td_state',
        ),
        migrations.CreateModel(
            name='TDState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_state', jsonfield.fields.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
