# Generated by Django 3.1.4 on 2021-01-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0051_auto_20201230_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCSVTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField(null=True)),
            ],
        ),
    ]
