# Generated by Django 3.1.4 on 2021-01-07 21:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0052_finalcsvtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcsv',
            name='buy_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_by_date',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='net_inst_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='sell_value',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_buys',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_inst',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='top10_sells',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsv',
            name='wealth_graph',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcsvtable',
            name='table',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostats',
            name='execute_portfolio',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostats',
            name='portfolio_constituents',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostats',
            name='portfolio_wealth_graph',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tdstate',
            name='td_state',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
